export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';

//player
export const GET_SONG_AUDIO = 'GET_SONG_AUDIO';
export const HIDE_SHOW_ANALYSER = 'HIDE_SHOW_ANALYSER';
export const UPDATE_PLAYER_PLAYLIST = 'UPDATE_PLAYER_PLAYLIST';
export const START_PLAYLIST = 'START_PLAYLIST';
export const PLAYLIST_QUEUE_NEXT = 'PLAYLIST_QUEUE_NEXT';
export const PLAYLIST_QUEUE_PREVIOUS = 'PLAYLIST_QUEUE_PREVIOUS';

//song
export const GET_NEW_SONGS = 'GET_NEW_SONGS';
export const GET_SONG_PAGING = 'GET_SONG_PAGING';
export const FETCH_SONG_SCROLL = 'FETCH_SONG_SCROLL';

//playList
export const GET_USER_PLAYLIST = 'GET_USER_PLAYLIST';
export const GET_PLAYLIST = 'GET_PLAYLIST';
export const CREATE_NEW_PLAYLIST = 'CREATE_NEW_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const REMOVE_SONG_FROM_PLAYLIST = 'REMOVE_SONG_FROM_PLAYLIST';

//albums
export const GET_NEW_ALBUMS = 'GET_NEW_ALBUMS';
export const GET_ALBUM_DETAIL = 'GET_ALBUM_DETAIL';
export const GET_ALBUM_SONGS = 'GET_ALBUM_SONGS';

//UI
export const UI_SEARCHING = 'UI_SEARCHING';

//search 
export const SEARCH = 'SEARCH';